services:
  react-app:
    build: ./Frontend
    ports:
      - "5000:5000"
    depends_on:
      - node-backend

  node-backend:
    build: ./Backend
    ports:
      - "3001:3001"
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:5000 #change if you set your own url for the frontend
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    depends_on:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"   # MQTT protocol
      #- "9001:9001"    WebSocket support (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log