version: '3'
services:
  react-app:
    build: ./Frontend
    ports:
      - "5000:5000"
  node-backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - CORS_ALLOWED_ORIGINS=http://your-frontend-domain.com